# Generated by Django 3.0.7 on 2021-04-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20210405_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.CharField(default='default:-1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'UNPAID'), ('paid', 'PAID'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED'), ('received', 'RECEIVED')], default='unpaid', max_length=255),
        ),
    ]
