# Generated by Django 2.2.14 on 2021-04-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20210408_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
