# Generated by Django 3.0.7 on 2021-04-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_remove_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='media/static/product'),
        ),
    ]
