# Generated by Django 3.0.7 on 2021-04-16 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0011_product_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('qa_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('unread', 'UNREAD'), ('viewed', 'VIEWED'), ('answered', 'ANSWERED'), ('solved', 'SOLVED')], default='unread', max_length=255)),
                ('satisfaction', models.IntegerField(choices=[('disappointed', 0), ('not really satisfied', 1), ('okay', 2), ('satisfied', 3), ('very satisfied', 4)], default='very satisfied')),
                ('type', models.CharField(choices=[('questions', 'QUESTION'), ('trace', 'TRACE'), ('answer', 'ANSWER')], default='questions', max_length=255)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
