# Generated by Django 2.2.14 on 2021-04-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Beijing', max_length=512),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default='1234567890'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
