# Generated by Django 2.0.5 on 2021-05-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0012_auto_20210421_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('quality', 'QUALITY'), ('delivery', 'DELIVERY'), ('service', 'SERVICE'), ('order', 'ORDER'), ('product', 'PRODUCT')], default='quality', max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('unread', 'UNREAD'), ('read', 'READ'), ('answered', 'ANSWERED')], default='unread', max_length=255)),
                ('satisfaction', models.IntegerField(default='5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('user', 'USER'), ('staff', 'STAFF')], default='user', max_length=20)),
                ('date', models.CharField(default=django.utils.timezone.now, max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Question')),
            ],
        ),
    ]
