# Generated by Django 2.0.5 on 2021-05-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='set_default',
            field=models.BooleanField(default=False),
        ),
    ]
