# Generated by Django 2.2.14 on 2021-04-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
